[workspace]
resolver = "2"
members = ["crates/hips-core", "crates/hips-server"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
repository = "https://github.com/hikarinagi/hips"
rust-version = "1.95"

[workspace.dependencies]
hips-core = { path = "crates/hips-core" }
thiserror = "2"
tracing = "0.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
